name: Vigor
options:
  bundleIdPrefix: com.vigor
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

schemes:
  Vigor:
    build:
      targets:
        Vigor: all
        VigorWidget: all
    run:
      config: Debug
      executable: Vigor

settings:
  base:
    DEVELOPMENT_TEAM: 4YN4S8KBCP
    CODE_SIGN_STYLE: Automatic

targets:
  Vigor:
    type: application
    platform: iOS
    sources:
      - path: Vigor
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: Vigor/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vigor.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Vigor/Vigor.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.vigor.shared
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.vigor.app
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.vigor.app
    dependencies:
      - target: VigorWidget
        embed: true

  VigorWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: VigorWidget
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: VigorWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vigor.app.widget
    entitlements:
      path: VigorWidget/VigorWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.vigor.shared
