name: Vigor
options:
  bundleIdPrefix: cloud.buggygames.vigor
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

schemes:
  Vigor:
    build:
      targets:
        Vigor: all
        VigorWidget: all
    run:
      config: Debug
      executable: Vigor

  VigorWatch:
    build:
      targets:
        VigorWatch: all
        VigorWatchWidget: all
    run:
      config: Debug
      executable: VigorWatch

settings:
  base:
    DEVELOPMENT_TEAM: 4YN4S8KBCP
    CODE_SIGN_STYLE: Automatic

targets:
  Vigor:
    type: application
    platform: iOS
    sources:
      - path: Vigor
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: Vigor/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.vigor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Vigor/Vigor.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.vigor
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.icloud-container-identifiers:
          - iCloud.cloud.buggygames.vigor
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)cloud.buggygames.vigor
    dependencies:
      - target: VigorWidget
        embed: true

  VigorWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: VigorWidget
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: VigorWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.vigor.widget
    entitlements:
      path: VigorWidget/VigorWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.vigor

  VigorWatch:
    type: application
    platform: watchOS
    sources:
      - path: VigorWatch
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: VigorWatch/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.vigor.watch
    entitlements:
      path: VigorWatch/VigorWatch.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.vigor
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    dependencies:
      - target: VigorWatchWidget
        embed: true

  VigorWatchWidget:
    type: app-extension
    platform: watchOS
    sources:
      - path: VigorWatchWidget
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: VigorWatchWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.vigor.watch.widget
    entitlements:
      path: VigorWatchWidget/VigorWatchWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.vigor
